/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "test_constants.h"

namespace testFunctions {

const testConstants g_test_constants;

testConstants::testConstants() {
}

} // namespace

